"""Update table

Revision ID: 078945cd9e4b
Revises: 80242425092f
Create Date: 2025-07-25 13:42:23.838203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078945cd9e4b'
down_revision = '80242425092f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unit_created_by_fkey', 'unit', type_='foreignkey')
    op.drop_column('unit', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('unit_created_by_fkey', 'unit', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###
