"""add created_at column tp unit_user tables

Revision ID: 07c0bae200de
Revises: 462adce1f3a8
Create Date: 2025-07-25 11:11:05.265865

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '07c0bae200de'
down_revision = '462adce1f3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit_user', 'updated_at')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS unaccent")
