"""create test model

Revision ID: 1856cb7145f8
Revises: f08b2dc8ee4e
Create Date: 2025-08-06 11:50:58.789001

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1856cb7145f8'
down_revision = 'f08b2dc8ee4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
