"""create event, partner, ...

Revision ID: 3ab3bc3345e8
Revises: d0eea768f6d8
Create Date: 2025-08-06 11:06:48.416959

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3ab3bc3345e8'
down_revision = 'd0eea768f6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
