"""Update table

Revision ID: 3fefe677d5cc
Revises: 078945cd9e4b
Create Date: 2025-07-25 14:17:53.553072

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3fefe677d5cc'
down_revision = '078945cd9e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'unit', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.drop_column('unit', 'created_by')
    # ### end Alembic commands ###
