"""Update table

Revision ID: 80242425092f
Revises: ccc6f6c4a1bb
Create Date: 2025-07-25 11:48:58.888820

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '80242425092f'
down_revision = 'ccc6f6c4a1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
