"""create test model

Revision ID: 8899d5e436ae
Revises: 1856cb7145f8
Create Date: 2025-08-06 11:51:24.033121

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8899d5e436ae'
down_revision = '1856cb7145f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
