"""create test model

Revision ID: 8e0f8ec9e964
Revises: 8899d5e436ae
Create Date: 2025-08-06 11:54:44.361667

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8e0f8ec9e964'
down_revision = '8899d5e436ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
