"""create test model

Revision ID: acd9f2e81ce2
Revises: 8e0f8ec9e964
Create Date: 2025-08-06 11:55:20.088690

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'acd9f2e81ce2'
down_revision = '8e0f8ec9e964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
