"""create event, partner, ... v3

Revision ID: c42b623b9c7a
Revises: 505e500c93ce
Create Date: 2025-08-06 11:36:22.002532

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c42b623b9c7a'
down_revision = '505e500c93ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
