"""Update table

Revision ID: ccc6f6c4a1bb
Revises: d7c6775ccd30
Create Date: 2025-07-25 11:45:50.055933

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ccc6f6c4a1bb'
down_revision = 'd7c6775ccd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
