"""create test model 1

Revision ID: d7484d86f0f4
Revises: 20821e1a3316
Create Date: 2025-08-06 13:50:59.503548

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd7484d86f0f4'
down_revision = '20821e1a3316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
