"""add unit and unit_user tables

Revision ID: d9cf6c8f2af9
Revises: c56939889577
Create Date: 2025-07-25 11:08:01.577686

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd9cf6c8f2af9'
down_revision = 'c56939889577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
