"""create event, partner, ... v6

Revision ID: f08b2dc8ee4e
Revises: 3fec13d627fd
Create Date: 2025-08-06 11:44:13.969939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08b2dc8ee4e'
down_revision = '3fec13d627fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
